// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWrr3U9f-zYv4cvGinWf_cY-qZJIlXdA8',
    appId: '1:325359761218:web:da4a14f58429afd6e27adb',
    messagingSenderId: '325359761218',
    projectId: 'sample-firebase-ai-app-6af00',
    authDomain: 'sample-firebase-ai-app-6af00.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-6af00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiHKQ2_OI9wBZ0UwiO_F-ar_Ewr5YxB3c',
    appId: '1:325359761218:android:af90cc42ccb655a4e27adb',
    messagingSenderId: '325359761218',
    projectId: 'sample-firebase-ai-app-6af00',
    storageBucket: 'sample-firebase-ai-app-6af00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAigd_aXDPYmfeN_carQh0gS5CzcnQ3Dbc',
    appId: '1:325359761218:ios:b8118d79145406e8e27adb',
    messagingSenderId: '325359761218',
    projectId: 'sample-firebase-ai-app-6af00',
    storageBucket: 'sample-firebase-ai-app-6af00.firebasestorage.app',
    iosBundleId: 'com.example.smartgarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAigd_aXDPYmfeN_carQh0gS5CzcnQ3Dbc',
    appId: '1:325359761218:ios:b8118d79145406e8e27adb',
    messagingSenderId: '325359761218',
    projectId: 'sample-firebase-ai-app-6af00',
    storageBucket: 'sample-firebase-ai-app-6af00.firebasestorage.app',
    iosBundleId: 'com.example.smartgarage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWrr3U9f-zYv4cvGinWf_cY-qZJIlXdA8',
    appId: '1:325359761218:web:46c04b6e2bf5fd38e27adb',
    messagingSenderId: '325359761218',
    projectId: 'sample-firebase-ai-app-6af00',
    authDomain: 'sample-firebase-ai-app-6af00.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-6af00.firebasestorage.app',
  );
}
